name: 'quran_app_flutter'
description: 'Quran app in flutter'
publish_to: 'none'
version: '0.0.1+3'
environment:
  sdk: '^3.6.0'
dependencies:
  flutter:
    sdk: 'flutter'
  flutter_localizations:
    sdk: 'flutter'
  quran: '^1.3.3'
  http: '^1.3.0'
  background_downloader: '^8.9.3'
  universal_io: '^2.2.2'
  queue: '^3.4.0'
  google_fonts: '^6.2.1'
  simple_gesture_detector: '^0.2.1'
  scroll_snap_list: '^0.9.1'
  flutter_displaymode: '^0.6.0'
  desktop_window: '^0.4.2'
  auto_size_text: '^3.0.0'
  page_transition: '^2.2.1'
  page_flip: '^0.2.3'
  audio_session: '^0.1.23'

  just_audio: '^0.9.43'
  media_kit: '^1.1.11'
  media_kit_libs_audio: ^1.0.5

  shared_preferences: '^2.3.5'
  percent_indicator: '^4.2.4'
  flutter_colorpicker: '^1.1.0'
  dio: '^5.7.0'
  path_provider: '^2.1.5'
  provider: '^6.1.2'
  sidebarx: '^0.17.1'
  measure_size_builder: '^1.0.3'
  flutter_launcher_icons: ^0.14.3
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  msix: '^3.16.8'
  inno_build: '^0.3.0'
  flutter_distributor: ^0.0.2
flutter:
  uses-material-design: true
  assets:
    - 'assets/images/hollow/bg.png'
  fonts:
    - family: 'pointer'
      fonts:
        - asset: 'assets/fonts/pointer.ttf'
    - family: 'arabicFont'
      fonts:
        - asset: 'assets/fonts/Roboto-Regular.ttf'
    - family: 'surahNames'
      fonts:
        - asset: 'assets/fonts/quran/surah-names/v1/sura_names.ttf'
    - family: 'page175'
      fonts:
        - asset: 'assets/fonts/quran/page175.ttf'
inno_build:
  app_id: '60c776c4-dd15-4ea3-b2fb-3b6a725a5853'

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/icon/icon.png"

  android: "launcher_icon"
  image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  image_path_ios: "assets/icon/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#000000"
    theme_color: "#000000"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/icon/icon.png"

  linux:
    generate: true
    image_path: "assets/icon/icon.png"

