/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
library;
import 'package:flutter/widgets.dart';

class PointerUp {
  PointerUp._();

  static const _kFontFam = 'pointer';
  static const String? _kFontPkg = null;

  static const IconData pointerUp =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
